# Generated by Django 5.0.6 on 2025-04-18 09:22

import django.core.validators
import django.db.models.deletion
import goodfood.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(db_index=True, max_length=256, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MaxLengthValidator(64), goodfood.validators.GoodfoodValidator()], verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodfood.categories', validators=[django.core.validators.MaxLengthValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
