# Generated by Django 5.2.5 on 2025-08-18 08:19

import apps.goodfood.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(db_index=True, max_length=256, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(256), apps.goodfood.validators.GoodfoodValidator()], verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(64), apps.goodfood.validators.GoodfoodValidator()], verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(256), apps.goodfood.validators.GoodfoodValidator()], verbose_name='Описание')),
                ('slugify_name', models.SlugField(allow_unicode=True, blank=True, max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='Slug может содержать только буквы, цифры, дефис и подчёркивания.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodfood.categories', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table_comment': 'База данных с рецептами блюд',
                'ordering': ['-time_created'],
                'get_latest_by': ['time_updated'],
            },
        ),
    ]
