# Generated by Django 5.0.6 on 2025-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='slugify_name',
            field=models.SlugField(blank=True, max_length=256, verbose_name='Слаг'),
        ),
    ]
