# Generated by Django 5.0.6 on 2025-04-18 12:48

import django.core.validators
import django.db.models.deletion
import goodfood.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0002_goods_slugify_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodfood.categories', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64), goodfood.validators.GoodfoodValidator()], verbose_name='Название'),
        ),
    ]
