# Generated by Django 5.0.6 on 2025-04-18 12:49

import django.core.validators
import django.db.models.deletion
import goodfood.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0003_alter_goods_category_alter_goods_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat',
            field=models.CharField(db_index=True, max_length=256, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodfood.categories', verbose_name='категория'),
        ),
    ]
