# Generated by Django 5.0.6 on 2025-04-27 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0006_alter_goods_slugify_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
