# Generated by Django 4.2.23 on 2025-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0007_goods_time_created_goods_time_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'get_latest_by': ['time_updated'], 'ordering': ['-time_created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelTableComment(
            name='goods',
            table_comment='База данных с рецептами блюд',
        ),
        migrations.AlterField(
            model_name='goods',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
