# Generated by Django 5.2.5 on 2025-10-09 07:56

import django.core.validators
import goodfood.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0008_alter_goods_options_alter_goods_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat',
            field=models.CharField(db_index=True, max_length=32, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(32), goodfood.validators.GoodfoodValidator()], verbose_name='категория'),
        ),
    ]
