# Generated by Django 5.0.6 on 2025-02-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=256, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=64, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodfood.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
