# Generated by Django 5.0.6 on 2025-03-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='product_name',
            new_name='name',
        ),
    ]
