# Generated by Django 5.0.6 on 2025-04-18 12:51

import django.core.validators
import goodfood.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0004_alter_categories_cat_alter_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat',
            field=models.CharField(db_index=True, max_length=256, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(256), goodfood.validators.GoodfoodValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(64), goodfood.validators.GoodfoodValidator()], verbose_name='Название'),
        ),
    ]
