# Generated by Django 5.0.6 on 2025-04-18 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodfood', '0005_alter_categories_cat_alter_goods_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slugify_name',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='Slug может содержать только буквы, цифры, дефис и подчёркивания.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
